### PR TITLE
fix(model): do not assume success when deleting a model process

### LINKED ISSUE #7962: Stopping a model assumes the process will be killed
**LocalAI version:** v3.9.0

**Environment, CPU architecture, OS, and Version:** See #7958 

**Describe the bug**

While working on #7958, I saw that there is a [faulty `defer`](https://github.com/mudler/LocalAI/blob/c88074a19e9318b6563f803069479a57614ecb53/pkg/model/process.go#L27) that removes the model from the model loader list. This `defer` assumes the model process will always be killed successfully, which is a bad assumption.

**To Reproduce**

Follow the steps in #7958 and notice that the model is removed from the model loader's model list even if the process isn't successfully killed.

**Expected behavior**

The model loader should not remove the model from its list unless killing the process succeeds.

**Logs**

**Additional context**

PR incoming

### PR DESCRIPTION
**Pull request by jroeber**
**Description**

This PR fixes #7962 

**Notes for Reviewers**

Related: #7958 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

File: pkg/model/process.go [hunk 1]
```diff
@@ -56,6 +55,10 @@ func (ml *ModelLoader) deleteProcess(s string) error {
 		xlog.Error("(deleteProcess) error while deleting process", "error", err, "model", s)
 	}
 
+	if err != nil {
```
Comment (mudler) [inline pkg/model/process.go]: Probably this should be the other way around
```suggestion
	if err == nil {
```

Comment (jroeber) [reply pkg/model/process.go]: My mistake. Force of habit! :man_facepalming:

**Comment by mudler** [comment]
good catch, thanks!
