### PR TITLE
Fix NVIDIA VRAM detection on WSL2 environments

### LINKED ISSUE #1893: [AIO] WSL detection for NVIDIA VRAM size is not working
**LocalAI version:**

quay.io/go-skynet/local-ai:master-aio-gpu-nvidia-cuda-12

**Environment, CPU architecture, OS, and Version:**

WSL2, Linux 75be0c1341b1 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

The AIO entrypoint says:
> Non-NVIDIA GPU detected. GPU memory size detection for non-NVIDIA GPUs is not supported in this script.
despite the GPU being an NVIDIA

**To Reproduce**

`docker run --rm -ti --gpus all quay.io/go-skynet/local-ai:master-aio-gpu-nvidia-cuda-12`

**Expected behavior**

> NVIDIA GPU detected. Attempting to find memory size...
> Total GPU Memory: 24576 MiB

**Additional context**

- [x] PR incoming

### PR DESCRIPTION
**Pull request by enricoros**
More robust single NVIDIA GPU memory detection, following the improved NVIDIA WSL2 detection patch yesterday #1891.

Tested and working on WSL2, Linux.

**Description**

This PR fixes #1893

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

File: aio/entrypoint.sh [hunk 1]
```diff
@@ -57,29 +57,33 @@ function detect_gpu() {
...
+            # if bigger than 8GB, use 16GB
+            #if [ "$nvidia_sm" -gt 8192 ]; then
+            #    GPU_SIZE=gpu-16g
+            #else
+            GPU_SIZE=gpu-8g
+            #fi
         else
-            echo "Unable to determine NVIDIA GPU memory size."
+            echo "Unable to determine NVIDIA GPU memory size. Falling back to CPU."
+            GPU_SIZE=cpu
```
Comment (mudler) [inline aio/entrypoint.sh:76]: I'd just go with the minimum gpu setup at this point (we have already detected the gpu at this point)

```suggestion
            GPU_SIZE=gpu-8g
```

**Review by mudler — APPROVED** [review]
