### PR TITLE
fix(health): do not require auth for /healthz and /readyz

### LINKED ISSUE #3655: ERR Server error error="missing or malformed API Key"
**LocalAI version:**
```shell
git show
commit 1f43678d5311e7bdc434768ea74c97e49a6ebc7e
``` 

**Environment, CPU architecture, OS, and Version:**
```shell
uname -a
Linux serveur-a.a.web.fr 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

**Describe the bug**
It look line my API_KEY is malformed. But I used the same one that it was working with before rebuilding LocalAI with the current commit. There is no documentation or command provided to generate a proper key. I have tried this:
```shell
echo "sk-$(tr -dc A-Za-z0-9\-\_ </dev/urandom | head -c 21)" 
```
I am not sure if it is the proper command?

**To Reproduce**

**Expected behavior**
Here is the way I install and use it.
```shell
git clone https://github.com/mudler/LocalAI.git
cd LocalAI
mkdir perso
```
In perso, I create a docker-compose.yml file and I fill it with the following content:
```yalm
services:
  ai-api:
    image: local-ai:master-cublas-cuda12-ffmpeg
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        IMAGE_TYPE: extras
        BUILD_TYPE: cublas
        CUDA_MAJOR_VERSION: 12
        EXTRA_BACKENDS: "backend/python/coqui
                         backend/python/parler-tts
                         backend/python/diffusers
                         backend/python/transformers-musicgen
                         backend/python/exllamal
                         backend/python/vall-e-x
                         backend/python/openvoice
                         backend/python/petals
                         backend/python/sentencetransformers
                         backend/python/exllama2
                         backend/python/transformers
                         backend/python/vllm
                         backend/python/autogptq
                         backend/python/bark
                         backend/python/rerankers
                         backend/python/mamba
                         "
        FFMPEG: true
        GO_TAGS: 'stablediffusion tts'
    container_name: ai-api
    restart: always # should this be on-failure ?
    tty: true # enable colorized logs
    # As initially LocalAI will download the models defined in PRELOAD_MODELS
    # you might need to tweak the healthcheck values here according to your network connection.
    # Here we give a timespan of 20m to download all the required files.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 20
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DEBUG=true
      - API_KEY=${API_KEY}
      - MODELS_PATH=/models
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all
      - CUDA_DEVICE_POOL_GPU_OVERRIDE=1
      # You can preload different models here as well.
      # See: https://github.com/go-skynet/model-gallery
#      - 'PRELOAD_MODELS=[
#                         {"url": "github:go-skynet/model-gallery/gpt4all-j.yaml", "name": "gpt-3.5-turbo"},
#                         {"url": "github:go-skynet/model-gallery/llama2-chat.yaml", "name": "llama2-chat"},
#                         {"url": "github:go-skynet/model-gallery/stablediffusion.yaml", "name": "stablediffusion"},
#                        ]'
      - THREADS=4
      - ADDRESS=0.0.0.0:8080
      - GO_TAGS='stablediffusion tts'
      - IMAGE_PATH=/tmp/generated/images
      - HUGGINGFACE_HUB_CACHE=/usr/local/huggingface
      - PYTHON_GRPC_MAX_WORKERS=4
      - LLAMACPP_PARALLEL=4
      - PARALLEL_REQUESTS=true
      - WATCHDOG_IDLE=true
      - WATCHDOG_BUSY=true
      - WATCHDOG_IDLE_TIMEOUT=5m
      - WATCHDOG_BUSY_TIMEOUT=5m
    volumes:
      - /media/cache/localai/models:/models:cached
      - /media/cache/localai/images:/tmp/generated/images
#    command: ["/usr/bin/local-ai" ]
    networks:
      - front
    labels:
      - traefik.enable=true
      # Entrypoint and TLS
      - traefik.http.routers.ai-api.entrypoints=http,https
      - traefik.http.routers.ai-api.rule=Host(`api.ai.web.fr`)
      - traefik.http.routers.ai-api.tls=true
      - traefik.http.routers.ai-api.tls.certresolver=le
      # Service
      - traefik.http.services.ai-api.loadbalancer.server.port=8080
      # Middlewares
      - traefik.http.routers.ai-api.middlewares=force-https,ai-api
      # Middlewares nc force https and adds additional headers
      - traefik.http.middlewares.force-https.redirectscheme.scheme=https
      - traefik.http.middlewares.force-https.redirectscheme.permanent=true
      - traefik.http.middlewares.ai-api.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.ai-api.headers.framedeny=true
      - traefik.http.middlewares.ai-api.headers.stsincludesubdomains=true
      - traefik.http.middlewares.ai-api.headers.stspreload=true
      - traefik.http.middlewares.ai-api.headers.stsseconds=15552000

  ai-ui:
    depends_on:
     ai-api:
        condition: service_healthy
#    image: ghcr.io/mckaywrigley/chatbot-ui:main
    image: ghcr.io/enricoros/big-agi
    container_name: ai-ui
#    ports:
#      - 3000:3000
    environment:
      HTTP_BASIC_AUTH_USERNAME: xxxxxxxxx
      HTTP_BASIC_AUTH_PASSWORD: xxxxxxxxx
    networks:
      - front
    labels:
      - traefik.enable=true
      # Entrypoint and TLS
      - traefik.http.routers.ai.entrypoints=http,https
      - traefik.http.routers.ai.rule=Host(`ai.web.fr`)
      - traefik.http.routers.ai.tls=true
      - traefik.http.routers.ai.tls.certresolver=le
      # Service
      - traefik.http.services.ai.loadbalancer.server.port=3000
      # Middlewares
      - traefik.http.routers.ai.middlewares=force-https,ai
      # Middlewares nc force https and adds additional headers
      - traefik.http.middlewares.force-https.redirectscheme.scheme=https
      - traefik.http.middlewares.force-https.redirectscheme.permanent=true
      - traefik.http.middlewares.ai.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.ai.headers.framedeny=true
      - traefik.http.middlewares.ai.headers.stsincludesubdomains=true
      - traefik.http.middlewares.ai.headers.stspreload=true
      - traefik.http.middlewares.ai.headers.stsseconds=15552000
```
then I fill up the .env file with the api key.
I launch:
```shell
docker compose build
docker compose up -d
```

**Logs**
```shell
ai-api  | 8:39AM DBG Extracting backend assets files to /tmp/localai/backend_data
ai-api  | 8:39AM DBG processing api keys runtime update
ai-api  | 8:39AM DBG processing external_backends.json
ai-api  | 8:39AM DBG external backends loaded from external_backends.json
ai-api  | 8:39AM INF [WatchDog] starting watchdog
ai-api  | 8:39AM INF core/startup process completed!
ai-api  | 8:39AM DBG No configuration file found at /tmp/localai/upload/uploadedFiles.json
ai-api  | 8:39AM DBG No configuration file found at /tmp/localai/config/assistants.json
ai-api  | 8:39AM DBG No configuration file found at /tmp/localai/config/assistantsFile.json
ai-api  | 8:39AM INF LocalAI API is listening! Please connect to the endpoint for API documentation. endpoint=http://0.0.0.0:8080
ai-api  | 8:40AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:40AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:40AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="364.984µs" method=GET status=500 url=/readyz
ai-api  | 8:40AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:40AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:41AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:41AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:41AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="79.085µs" method=GET status=500 url=/readyz
ai-api  | 8:41AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:41AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:42AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:42AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:42AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="88.384µs" method=GET status=500 url=/readyz
ai-api  | 8:42AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:42AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:43AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:43AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:43AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="108.185µs" method=GET status=500 url=/readyz
ai-api  | 8:43AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:43AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:44AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:44AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:44AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="97.028µs" method=GET status=500 url=/readyz
ai-api  | 8:44AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:44AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:45AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:45AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:45AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="110.671µs" method=GET status=500 url=/readyz
ai-api  | 8:45AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:45AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:46AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:46AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:46AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="86.131µs" method=GET status=500 url=/readyz
ai-api  | 8:46AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:46AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:47AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:47AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:47AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="118.019µs" method=GET status=500 url=/readyz
ai-api  | 8:47AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:47AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:48AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:48AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:48AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="133.675µs" method=GET status=500 url=/readyz
ai-api  | 8:48AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:48AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:49AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:49AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:49AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="75.38µs" method=GET status=500 url=/readyz
ai-api  | 8:49AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:49AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:50AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:50AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:50AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="195.602µs" method=GET status=500 url=/readyz
ai-api  | 8:50AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:50AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:51AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:51AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:51AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="120.899µs" method=GET status=500 url=/readyz
ai-api  | 8:51AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:51AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:52AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:52AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:52AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="116.087µs" method=GET status=500 url=/readyz
ai-api  | 8:52AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:52AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:53AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:53AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:53AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="86.127µs" method=GET status=500 url=/readyz
ai-api  | 8:53AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:53AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:54AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:54AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:54AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="143.126µs" method=GET status=500 url=/readyz
ai-api  | 8:54AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:54AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:55AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:55AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:55AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="83.552µs" method=GET status=500 url=/readyz
ai-api  | 8:55AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:55AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:56AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:56AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:56AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="119.09µs" method=GET status=500 url=/readyz
ai-api  | 8:56AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:56AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:57AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:57AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:57AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="86.371µs" method=GET status=500 url=/readyz
ai-api  | 8:57AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:57AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:58AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:58AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:58AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="113.362µs" method=GET status=500 url=/readyz
ai-api  | 8:58AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:58AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:59AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:59AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 8:59AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="108.367µs" method=GET status=500 url=/readyz
ai-api  | 8:59AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 8:59AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:00AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:00AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:00AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="82.688µs" method=GET status=500 url=/readyz
ai-api  | 9:00AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:00AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:01AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:01AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:01AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="76.79µs" method=GET status=500 url=/readyz
ai-api  | 9:01AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:01AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:02AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:02AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:02AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="91.477µs" method=GET status=500 url=/readyz
ai-api  | 9:02AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:02AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:03AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:03AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:03AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="157.021µs" method=GET status=500 url=/readyz
ai-api  | 9:03AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:03AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:04AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:04AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:04AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="152.577µs" method=GET status=500 url=/readyz
ai-api  | 9:04AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:04AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:05AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:05AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:05AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="106.81µs" method=GET status=500 url=/readyz
ai-api  | 9:05AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:05AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:06AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:06AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:06AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="131.895µs" method=GET status=500 url=/readyz
ai-api  | 9:06AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:06AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:07AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:07AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:07AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="92.168µs" method=GET status=500 url=/readyz
ai-api  | 9:07AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:07AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:08AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:08AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:08AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="126.116µs" method=GET status=500 url=/readyz
ai-api  | 9:08AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:08AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:09AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:09AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:09AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:09AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:09AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="62.405µs" method=GET status=500 url=/readyz
ai-api  | 9:10AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:10AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:10AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:10AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:10AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="131.041µs" method=GET status=500 url=/readyz
ai-api  | 9:11AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:11AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:11AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:11AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:11AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="74.592µs" method=GET status=500 url=/readyz
ai-api  | 9:12AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:12AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:12AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:12AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:12AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="231.669µs" method=GET status=500 url=/readyz
ai-api  | 9:13AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:13AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:13AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:13AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:13AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="148.965µs" method=GET status=500 url=/readyz
ai-api  | 9:14AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:14AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:14AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:14AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:14AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="137.016µs" method=GET status=500 url=/readyz
ai-api  | 9:15AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:15AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:15AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:15AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:15AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="94.618µs" method=GET status=500 url=/readyz
ai-api  | 9:16AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:16AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:16AM DBG [WatchDog] Watchdog checks for busy connections
ai-api  | 9:16AM DBG [WatchDog] Watchdog checks for idle connections
ai-api  | 9:16AM ERR Server error error="missing or malformed API Key" ip=127.0.0.1 latency="131.002µs" method=GET status=500 url=/readyz
```

**Additional context**
I am not sure if it is a bug, But as I mentioned before, It was working fine before I update the commit to rebuild the container???
Regards
Pierre

### PR DESCRIPTION
**Pull request by mudler**
**Description**

This PR fixes #3655

**Notes for Reviewers**

Introduced in https://github.com/mudler/LocalAI/pull/3476

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by dave-gray101 — APPROVED** [review]
Added a comment so I remember why we did this... otherwise looks sound to me

File: core/http/app.go [hunk 1]
```diff
@@ -121,6 +121,9 @@ func App(cl *config.BackendConfigLoader, ml *model.ModelLoader, appConfig *confi
 		})
 	}
 
+ // Health Checks should always be exempt from auth, so register these first
```
Comment (mudler) [inline core/http/app.go:124]: :+1:
